# Generated by Django 5.2.7 on 2025-10-31 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField(help_text='{"en": "...", "fr": "...", "ar": "..."}')),
                ('description', models.JSONField()),
                ('instructions', models.JSONField(help_text='{"en": [...], "fr": [...], "ar": [...]}')),
                ('category', models.JSONField()),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('demo_video_url', models.URLField(blank=True)),
                ('target_muscles', models.JSONField(default=list)),
            ],
        ),
    ]
