# Generated by Django 5.2.7 on 2025-11-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField()),
                ('description', models.JSONField()),
                ('instructions', models.JSONField()),
                ('category', models.JSONField()),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('demo_video_url', models.URLField(blank=True)),
                ('target_muscles', models.JSONField(default=list)),
                ('main_muscle', models.CharField(default='Full Body', max_length=50)),
                ('equipment', models.CharField(default='Bodyweight', max_length=50)),
                ('mechanics', models.CharField(default='Compound', max_length=20)),
            ],
        ),
    ]
