# Generated by Django 5.2.7 on 2025-10-31 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialties', models.JSONField(default=dict)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('bio', models.JSONField(default=dict)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='coaches/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
